### ISSUE TITLE
Mu and Std calculation in forward pass

### ISSUE THREAD

**Issue by talent404** [fe1ixxu/VT-STOWER#1]
```
        mu = latent
        for layer in self.fc_mu:
            mu = layer(latent, mask)

        log_var = latent
        for layer in self.fc_mu:
            log_var = layer(latent, mask)
```

https://github.com/fe1ixxu/VT-STOWER/blob/a68db2ce64ed3f9ca54a2f9ad6d4ace2920ee241/fairseq/models/transformer.py#L1158

Should it not be self.fc_var instead of self.fc_mu for log_var computation?

**Comment by fe1ixxu** [comment]
Thank you! Yes, you are correct. It should be a typo when we clean up the code. Fixed now.
